name: Cleanup Database Duplicates

on:
    schedule:
      - cron: '16 */3 * * *'  # Run every 3 hours and 16 minutes
    workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    env:
      TURSO_DATABASE_URL: libsql://main-goodoffers-db-offren.turso.io
      TURSO_AUTH_TOKEN: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3MzExMjg1MzYsImlkIjoiNzgwNDY1YjktNzc5Yi00YjNhLTgwYzUtZWVlN2Q5NzUxNWI3In0.v7X1lyPpxDOUk123E3EHjTBJ8_LBtFvwOkVylqz9edu2dQjznSe87oBFtRSrNk1PD6OCpmNoiBP31NnGY4HEDA
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run database cleanup
        run: python db_cleanup.py